### ISSUE TITLE
Fix favicon on gh-pages

### ISSUE THREAD

**Issue by terriann** [terriann/CsvToMarkdownTable#5]
The favicon on gh-pages should be updated to have a transparent background

![capture](https://user-images.githubusercontent.com/316632/27385165-a5b10834-565f-11e7-80e2-1987dbfded95.PNG)

**Comment by donatj** [comment]
![favicon](https://user-images.githubusercontent.com/133747/28224228-f08c314e-6893-11e7-84fa-2a6413c3c98d.png)

Here is your favicon.png with a transparent background. I would have simply made a pull request but github won't let me fork a fork of my own project for some reason 😉 

I've been pulling in some of your recent changes into my original version. Tests and what not. Wondering if you'd like me to cite you? I learned how to set up coveralls from your changes, which is **awesome**!

**Comment by terriann** [comment]
Thanks @donatj! If you'd like to cite me that's cool but you don't have to. I'm just glad you learned a bunch from what I setup on this fork.  I was really excited to try and apply a bunch of new things I've learned recently and this project was perfect cause it's easy to get near-full coverage on a brief script 👍 

If you have any questions or come up with tests that I'm missing in mine feel free to create an issue to let me know!
